version: "3.8"

services:
  gateway:
    build: ./gateway
    container_name: gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
    depends_on:
      - server

  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - TZ:="Europe/Moscow"
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit?user=postgres&password=iamroot
  #      - SPRING_DATASOURCE_USER=postgres
  #      - SPRING_DATASOURCE_PASSWORD=iamroot

  db:
    image: postgres:14
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot